/* Fotos dos artistas (Deezer, match exato do nome). Gerado automaticamente. Apaga entradas erradas à vontade. */
FESTIVAL.images = {
  "The Royston Club": "assets/artists/the-royston-club.jpg",
  "A Perfect Circle": "assets/artists/a-perfect-circle.jpg",
  "Nick Cave & The Bad Seeds": "assets/artists/nick-cave-the-bad-seeds.jpg",
  "Twenty One Pilots": "assets/artists/twenty-one-pilots.jpg",
  "Sonya": "assets/artists/sonya.jpg",
  "Dogstar": "assets/artists/dogstar.jpg",
  "Alabama Shakes": "assets/artists/alabama-shakes.jpg",
  "Xinobi": "assets/artists/xinobi.jpg",
  "Matt Berninger": "assets/artists/matt-berninger.jpg",
  "Tomora": "assets/artists/tomora.jpg",
  "Maria Lui": "assets/artists/maria-lui.jpg",
  "Saya Noé": "assets/artists/saya-noe.jpg",
  "Linka Moja": "assets/artists/linka-moja.jpg",
  "Gui Aly": "assets/artists/gui-aly.jpg",
  "Rumia": "assets/artists/rumia.jpg",
  "Polo & Pan": "assets/artists/polo-pan.jpg",
  "Midnight Generation": "assets/artists/midnight-generation.jpg",
  "Neon Soho": "assets/artists/neon-soho.jpg",
  "Duques do Precariado": "assets/artists/duques-do-precariado.jpg",
  "Hetta": "assets/artists/hetta.jpg",
  "Diana Vilarinho": "assets/artists/diana-vilarinho.jpg",
  "Namorados da Cidade": "assets/artists/namorados-da-cidade.jpg",
  "The Warning": "assets/artists/the-warning.jpg",
  "Skunk Anansie": "assets/artists/skunk-anansie.jpg",
  "Wolf Alice": "assets/artists/wolf-alice.jpg",
  "Foo Fighters": "assets/artists/foo-fighters.jpg",
  "Call Me": "assets/artists/call-me.jpg",
  "Palaye Royale": "assets/artists/palaye-royale.jpg",
  "Jehnny Beth": "assets/artists/jehnny-beth.jpg",
  "The War on Drugs": "assets/artists/the-war-on-drugs.jpg",
  "Zara Larsson": "assets/artists/zara-larsson.jpg",
  "Stresshead": "assets/artists/stresshead.jpg",
  "La Fleur": "assets/artists/la-fleur.jpg",
  "Chris Luno": "assets/artists/chris-luno.jpg",
  "Fiona Kraft": "assets/artists/fiona-kraft.jpg",
  "Digitalism": "assets/artists/digitalism.jpg",
  "SBTRKT": "assets/artists/sbtrkt.jpg",
  "Inês Sousa": "assets/artists/ines-sousa.jpg",
  "Picas": "assets/artists/picas.jpg",
  "Constança Quinteiro": "assets/artists/constanca-quinteiro.jpg",
  "Mutu": "assets/artists/mutu.jpg",
  "Fado Máfia": "assets/artists/fado-mafia.jpg",
  "Ana Sofia Varela": "assets/artists/ana-sofia-varela.jpg",
  "Soundproof": "assets/artists/soundproof.jpg",
  "Madalena Malveiro": "assets/artists/madalena-malveiro.jpg",
  "Hélder Machado": "assets/artists/helder-machado.jpg",
  "Joana Gama": "assets/artists/joana-gama.jpg",
  "Francisco Menezes": "assets/artists/francisco-menezes.jpg",
  "Gilmário Vemba": "assets/artists/gilmario-vemba.jpg",
  "Don West": "assets/artists/don-west.jpg",
  "Teddy Swims": "assets/artists/teddy-swims.jpg",
  "Lorde": "assets/artists/lorde.jpg",
  "Florence + The Machine": "assets/artists/florence-the-machine.jpg",
  "Buraka Som Sistema": "assets/artists/buraka-som-sistema.jpg",
  "Rita Cortezão": "assets/artists/rita-cortezao.jpg",
  "Florence Road": "assets/artists/florence-road.jpg",
  "Alessi Rose": "assets/artists/alessi-rose.jpg",
  "Pixies": "assets/artists/pixies.jpg",
  "Noiserv": "assets/artists/noiserv.jpg",
  "Zimmer90": "assets/artists/zimmer90.jpg",
  "Fidju Kitxora": "assets/artists/fidju-kitxora.jpg",
  "Pedro da Linha": "assets/artists/pedro-da-linha.jpg",
  "Deize Tigrona": "assets/artists/deize-tigrona.jpg",
  "Arthi": "assets/artists/arthi.jpg",
  "Titica": "assets/artists/titica.jpg",
  "Modeselektor": "assets/artists/modeselektor.jpg",
  "Esteves Sem Metafísica": "assets/artists/esteves-sem-metafisica.jpg",
  "Razy": "assets/artists/razy.jpg",
  "Redoma": "assets/artists/redoma.jpg",
  "Sheri Vari": "assets/artists/sheri-vari.jpg",
  "Valéria": "assets/artists/valeria.jpg",
  "Beatriz Felício": "assets/artists/beatriz-felicio.jpg",
  "Raio X": "assets/artists/raio-x.jpg",
  "Catarina Rocha": "assets/artists/catarina-rocha.jpg",
  "Joana Oliveira": "assets/artists/joana-oliveira.jpg",
  "Vitor Costa": "assets/artists/vitor-costa.jpg",
  "Dagu": "assets/artists/dagu.jpg",
  "Hugo Sousa": "assets/artists/hugo-sousa.jpg"
};
