/* Descrições dos artistas (fonte: guia enviado pelo João). Gerado. */
FESTIVAL.bios = {
  "The Royston Club": "Banda galesa de indie rock em forte ascensão, com guitarras dinâmicas e melodias muito cativantes.",
  "A Perfect Circle": "Supergrupo norte-americano de rock alternativo e metal progressivo fundado por Billy Howerdel e Maynard James Keenan.",
  "Nick Cave & The Bad Seeds": "O carismático Nick Cave lidera uma das mais intensas e teatrais bandas de rock alternativo e pós-punk do mundo.",
  "Twenty One Pilots": "Duo norte-americano que cruza alt-pop, hip-hop, eletrónica e indie com narrativas e conceitos visuais profundos.",
  "The Warning": "Power trio de rock formado por três irmãs mexicanas, um fenómeno global pelos seus riffs enérgicos.",
  "Skunk Anansie": "Ícones do rock alternativo britânico dos anos 90, liderados pela eletrizante Skin, com mensagens politizadas e som cru.",
  "Wolf Alice": "Aclamada banda britânica vencedora do Mercury Prize que equilibra guitarras grunge com dream pop etéreo.",
  "Foo Fighters": "Uma das maiores e mais amadas bandas de rock de estádio do planeta, liderada pelo icónico Dave Grohl.",
  "Don West": "Cantautor australiano focado em R&B, soul e rock alternativo, com uma voz marcante e calorosa.",
  "Teddy Swims": "Fenómeno vocal que mistura soul, country, pop e R&B com uma presença emocional arrebatadora.",
  "Lorde": "Cantautora neozelandesa que redefiniu o pop alternativo moderno com composições confessionais e minimalistas.",
  "Florence + The Machine": "Liderados pela carismática Florence Welch, entregam um indie pop barroco repleto de harpas, tambores e misticismo.",
  "Buraka Som Sistema": "O histórico coletivo português regressa com a sua fusão revolucionária de kuduro angolano e eletrónica global.",
  "Sonya": "Revelação de eletrónica alternativa, com batidas minimalistas e texturas vocais sombrias.",
  "Dogstar": "Banda de rock alternativo de Los Angeles reativada recentemente, famosa por contar com Keanu Reeves no baixo.",
  "Alabama Shakes": "Aclamado grupo de blues-rock e roots soul norte-americano, conhecido pela intensidade instrumental e vocal.",
  "Xinobi": "O produtor português Bruno Cardoso apresenta o seu espetáculo eletrónico ao vivo que funde house, disco e techno.",
  "Matt Berninger": "O vocalista dos The National foca-se no seu aclamado repertório a solo de indie rock barroco e melancólico.",
  "Tomora": "Produtor focado em techno melódico e deep house atmosférico, ideal para o final de noite.",
  "Call Me": "Projeto indie pop lo-fi emergente, focado em texturas acústicas e sintetizadores nostálgicos.",
  "Palaye Royale": "Irmãos canadianos que fundem fashion-rock, glam punk e britpop com uma imagem artística exuberante.",
  "Jehnny Beth": "A carismática ex-vocalista das Savages apresenta o seu projeto industrial-punk a solo, de batidas abrasivas.",
  "The War on Drugs": "Banda norte-americana vencedora de Grammy que cruza indie rock expansivo, americana e synth-pop nostálgico.",
  "Zara Larsson": "Superestrela pop sueca de renome mundial, com grandes hinos de pista e coreografias dinâmicas.",
  "Rita Cortezão": "Cantautora nacional do espectro pop-folk alternativo intimista, cantado em português.",
  "Florence Road": "Grupo britânico revelação assente no indie rock de guitarras melódicas e harmonias vocais cuidadas.",
  "Alessi Rose": "Promessa da pop alternativa britânica atual, escreve canções confessionais e orelhudas sobre a juventude.",
  "Pixies": "Lendas do rock alternativo norte-americano cuja dinâmica ruidoso-calmo influenciou gerações.",
  "Noiserv": "O multi-instrumentista português David Santos cria mundos sonoros complexos com loops e brinquedos musicais.",
  "Zimmer90": "Duo alemão de indie pop eletrónico e nu-disco, viral pelos seus ritmos relaxantes e atmosféricos.",
  "Maria Lui": "Prodígio nacional focado em R&B eletrónico e soul espacial.",
  "Saya Noé": "Artista synth-pop húngara, de ambientes lo-fi e eletrónica sombria.",
  "Linka Moja": "Nova sonoridade pop urbana nacional, com influências afrobeat e trap.",
  "Gui Aly": "Cantautor pop-rock português focado em melodias indie acústicas modernas.",
  "Rumia": "Pop eletrónica polaca delicada, assente em piano e sintetizadores cinemáticos.",
  "Polo & Pan": "Renomado duo francês, com sonoridade house e disco tropical muito festiva.",
  "Midnight Generation": "Banda mexicana que revitaliza o funk e o nu-disco clássico com sintetizadores retro.",
  "Stresshead": "Techno industrial agressivo, de beats eletrónicos abrasivos e ritmo acelerado.",
  "La Fleur": "DJ e produtora sueca de prestígio no house underground e techno profundo.",
  "Chris Luno": "Produtor de deep house melódico e orgânico, famoso pelos DJ sets ao ar livre.",
  "Fiona Kraft": "DJ em ascensão na eletrónica global, cruza afro-house com techno progressivo.",
  "Digitalism": "O lendário duo alemão combina ritmos indie-rock com electro-house pesado.",
  "SBTRKT": "O mestre do post-dubstep britânico traz um DJ set eclético cheio de UK garage.",
  "Fidju Kitxora": "Fusão afrobeat cabo-verdiana cruzada com texturas eletrónicas urbanas.",
  "Pedro da Linha": "Produtor chave da eletrónica lisboeta, desconstrói kuduro, tarraxinha e funk.",
  "Deize Tigrona": "Uma das vozes mais icónicas e pioneiras do funk carioca das favelas do Rio.",
  "Arthi": "DJ britânica focada em dancehall vibrante, reggaeton, UK garage e batidas afro.",
  "Titica": "A diva e grande ícone do kuduro angolano contemporâneo, com uma performance cénica fortíssima.",
  "Modeselektor": "Famoso duo berlinense de eletrónica experimental que mistura IDM, techno pesado e hip-hop.",
  "Deixa Rolá": "Coletivo nacional dedicado ao samba de roda e à música popular brasileira.",
  "Neon Soho": "Trio português de synth-pop e eletrónica melódica dançável, com alma soul.",
  "Duques do Precariado": "Rock alternativo nacional satírico, com forte pendor de intervenção social.",
  "Hetta": "Banda nacional de math-core e screamo, marcada pela energia caótica em palco.",
  "Rita Maia": "DJ e investigadora musical, com sets ricos em ritmos da diáspora africana e clubbing global.",
  "Inês Sousa": "Jazz vocal e pop acústica intimista, interpretada em português.",
  "Picas": "Jovem cantautora portuguesa de pop alternativa, de voz doce e melancólica.",
  "Ellis Ferrére": "Produtora eletrónica experimental, focada em paisagens sonoras e techno lo-fi.",
  "Constança Quinteiro": "Indie pop nacional e fado-folk, focado em texturas acústicas delicadas.",
  "Mutu": "Projeto nacional de eletrónica escura fundida com elementos da música tradicional portuguesa.",
  "Esteves Sem Metafísica": "Projeto nacional de poesia musicada e rock alternativo de garagem.",
  "Suzana Francês": "Fusão de folk contemporâneo, jazz e fado melódico.",
  "Razy": "Produtor de hip-hop e batidas eletrónicas, focado no grime e drill nacional.",
  "Redoma": "Duo de rap e eletrónica experimental nacional, de batidas industriais e rimas afiadas.",
  "Sheri Vari": "DJ nacional especializada em electro clássico, techno de Detroit e synth-wave industrial."
};
